- name: host
  shell: hostname
  register: host

- name: Copy Test
  copy:
    src: scripts/test.py
    dest: /home/jetson/test.py
    
- name: Creates a cron file under /etc/cron.d
  cron:
    name: "Update";
    user: "root";
    minute: 30;
    job: "sudo apt update";

