- name: host
  shell: hostname
  register: host

- name: Copy Test
  copy:
    src: scripts/test.py
    dest: /home/jetson/test.py
    
- name: Creates a cron file under /etc/cron.d
  cron:
    name: "Dummy Ansible"
    user: "root"
    minute: 5
    job: "/usr/bin/ansible-pull -o --skip-tags -U https://github.com/imrans55/griff_test.git"

